/*
 * Copyright (C) 2016 ~ 2018 Deepin Technology Co., Ltd.
 *               2016 ~ 2018 dragondjf
 *
 * Author:     dragondjf<dingjiangfeng@deepin.com>
 *
 * Maintainer: dragondjf<dingjiangfeng@deepin.com>
 *             zccrs<zhangjide@deepin.com>
 *             Tangtong<tangtong@deepin.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "dfilemenu.h"
#include "dfmevent.h"

#include "waylandutils.h"

#include <QGuiApplication>
#include <QCursor>
#include <QScreen>
#include <QWidget>

DFileMenu::DFileMenu(QWidget *parent)
    : QMenu(parent)
{

}

const QSharedPointer<DFMMenuActionEvent> DFileMenu::makeEvent(DFMGlobal::MenuAction action) const
{
    DFMMenuActionEvent *event = new DFMMenuActionEvent(m_sender, this, m_currentUrl, m_selectedUrls, action);

    event->setWindowId(m_eventId);

    return QSharedPointer<DFMMenuActionEvent>(event);
}

void DFileMenu::setEventData(const DUrl &currentUrl, const DUrlList &selectedUrls, quint64 eventId, const QObject *sender)
{
    m_currentUrl = currentUrl;
    m_selectedUrls = selectedUrls;
    m_eventId = eventId;
    m_sender = sender;
}

QAction *DFileMenu::actionAt(int index) const
{
    return actions().value(index);
}

QAction *DFileMenu::actionAt(const QString &text) const
{
    for (QAction *action : actions()) {
        if (action->text() == text) {
            return action;
        }
    }

    return Q_NULLPTR;
}

QAction *DFileMenu::exec()
{
    QPoint pos = QCursor::pos();
    if (WaylandUtils::isWaylandPlatform()) {
        // Keep the output selected by the widget that opened the menu.  At a
        // shared screen edge QGuiApplication::screenAt(cursor) is ambiguous,
        // while m_sender is the CanvasGridView/DFileView that received the
        // context-menu event.  Store the name as well because the desktop
        // process converts QMenu into a layer-shell surface during Show.
        const QWidget *senderWidget = qobject_cast<const QWidget *>(m_sender);
        QScreen *targetScreen = senderWidget ? senderWidget->screen() : nullptr;
        qWarning() << "GXDE_POPUP_TRACE exec"
                   << "cursor" << QCursor::pos()
                   << "sender" << senderWidget
                   << "senderGeometry" << (senderWidget ? senderWidget->geometry() : QRect())
                   << "targetScreen" << (targetScreen ? targetScreen->name() : QString())
                   << "targetGeometry" << (targetScreen ? targetScreen->geometry() : QRect());
        if (targetScreen) {
            // Menus generated by DFileMenuManager have no QWidget parent.
            // QWindow::setScreen() changes the public QScreen value, but for
            // an unparented Qt::Popup the Wayland platform window can keep the
            // output selected when it was first created.  LayerShellQt then
            // sends that stale wl_output to the compositor.  Give the popup
            // the view that received the context-menu event as its real
            // transient parent before native creation.
            setParent(const_cast<QWidget *>(senderWidget), Qt::Popup);
            setScreen(targetScreen);
            setProperty("_gxde_popup_screen", targetScreen->name());
        }

        pos -= QPoint(16, 16);
    }
    return QMenu::exec(pos);
}

quint64 DFileMenu::eventId() const
{
    return m_eventId;
}

QSet<DFMGlobal::MenuAction> DFileMenu::ignoreMenuActions() const
{
    return m_ignoreMenuActions;
}

void DFileMenu::setIgnoreMenuActions(const QSet<DFMGlobal::MenuAction> &ignoreMenuActions)
{
    m_ignoreMenuActions = ignoreMenuActions;
}

DUrlList DFileMenu::selectedUrls() const
{
    return m_selectedUrls;
}
