// This file was generated by qtwaylandscanner
// source file is treeland-dde-shell-v1.xml

#include "qwayland-treeland-dde-shell-v1.h"

QT_BEGIN_NAMESPACE
QT_WARNING_PUSH
QT_WARNING_DISABLE_GCC("-Wmissing-field-initializers")

namespace QtWayland {

static inline void *wlRegistryBind(struct ::wl_registry *registry, uint32_t name, const struct ::wl_interface *interface, uint32_t version)
{
    const uint32_t bindOpCode = 0;
#if (WAYLAND_VERSION_MAJOR == 1 && WAYLAND_VERSION_MINOR > 10) || WAYLAND_VERSION_MAJOR > 1
    return (void *) wl_proxy_marshal_constructor_versioned((struct wl_proxy *) registry,
        bindOpCode, interface, version, name, interface->name, version, nullptr);
#else
    return (void *) wl_proxy_marshal_constructor((struct wl_proxy *) registry,
        bindOpCode, interface, name, interface->name, version, nullptr);
#endif
}

    treeland_dde_shell_manager_v1::treeland_dde_shell_manager_v1(struct ::wl_registry *registry, int id, int version)
    {
        init(registry, id, version);
    }

    treeland_dde_shell_manager_v1::treeland_dde_shell_manager_v1(struct ::treeland_dde_shell_manager_v1 *obj)
        : m_treeland_dde_shell_manager_v1(obj)
    {
    }

    treeland_dde_shell_manager_v1::treeland_dde_shell_manager_v1()
        : m_treeland_dde_shell_manager_v1(nullptr)
    {
    }

    treeland_dde_shell_manager_v1::~treeland_dde_shell_manager_v1()
    {
    }

    void treeland_dde_shell_manager_v1::init(struct ::wl_registry *registry, int id, int version)
    {
        m_treeland_dde_shell_manager_v1 = static_cast<struct ::treeland_dde_shell_manager_v1 *>(wlRegistryBind(registry, id, &treeland_dde_shell_manager_v1_interface, version));
    }

    void treeland_dde_shell_manager_v1::init(struct ::treeland_dde_shell_manager_v1 *obj)
    {
        m_treeland_dde_shell_manager_v1 = obj;
    }

    treeland_dde_shell_manager_v1 *treeland_dde_shell_manager_v1::fromObject(struct ::treeland_dde_shell_manager_v1 *object)
    {
        return static_cast<treeland_dde_shell_manager_v1 *>(treeland_dde_shell_manager_v1_get_user_data(object));
    }

    bool treeland_dde_shell_manager_v1::isInitialized() const
    {
        return m_treeland_dde_shell_manager_v1 != nullptr;
    }

    const struct wl_interface *treeland_dde_shell_manager_v1::interface()
    {
        return &::treeland_dde_shell_manager_v1_interface;
    }

    struct ::treeland_dde_shell_surface_v1 *treeland_dde_shell_manager_v1::get_shell_surface(struct ::wl_surface *surface)
    {
        return treeland_dde_shell_manager_v1_get_shell_surface(
            m_treeland_dde_shell_manager_v1,
            surface);
    }

    void treeland_dde_shell_manager_v1::destroy()
    {
        treeland_dde_shell_manager_v1_destroy(
            m_treeland_dde_shell_manager_v1);
        m_treeland_dde_shell_manager_v1 = nullptr;
    }

    treeland_dde_shell_surface_v1::treeland_dde_shell_surface_v1(struct ::wl_registry *registry, int id, int version)
    {
        init(registry, id, version);
    }

    treeland_dde_shell_surface_v1::treeland_dde_shell_surface_v1(struct ::treeland_dde_shell_surface_v1 *obj)
        : m_treeland_dde_shell_surface_v1(obj)
    {
    }

    treeland_dde_shell_surface_v1::treeland_dde_shell_surface_v1()
        : m_treeland_dde_shell_surface_v1(nullptr)
    {
    }

    treeland_dde_shell_surface_v1::~treeland_dde_shell_surface_v1()
    {
    }

    void treeland_dde_shell_surface_v1::init(struct ::wl_registry *registry, int id, int version)
    {
        m_treeland_dde_shell_surface_v1 = static_cast<struct ::treeland_dde_shell_surface_v1 *>(wlRegistryBind(registry, id, &treeland_dde_shell_surface_v1_interface, version));
    }

    void treeland_dde_shell_surface_v1::init(struct ::treeland_dde_shell_surface_v1 *obj)
    {
        m_treeland_dde_shell_surface_v1 = obj;
    }

    treeland_dde_shell_surface_v1 *treeland_dde_shell_surface_v1::fromObject(struct ::treeland_dde_shell_surface_v1 *object)
    {
        return static_cast<treeland_dde_shell_surface_v1 *>(treeland_dde_shell_surface_v1_get_user_data(object));
    }

    bool treeland_dde_shell_surface_v1::isInitialized() const
    {
        return m_treeland_dde_shell_surface_v1 != nullptr;
    }

    const struct wl_interface *treeland_dde_shell_surface_v1::interface()
    {
        return &::treeland_dde_shell_surface_v1_interface;
    }

    void treeland_dde_shell_surface_v1::destroy()
    {
        treeland_dde_shell_surface_v1_destroy(
            m_treeland_dde_shell_surface_v1);
        m_treeland_dde_shell_surface_v1 = nullptr;
    }

    void treeland_dde_shell_surface_v1::set_surface_position(int32_t x, int32_t y)
    {
        treeland_dde_shell_surface_v1_set_surface_position(
            m_treeland_dde_shell_surface_v1,
            x,
            y);
    }

    void treeland_dde_shell_surface_v1::set_role(uint32_t role)
    {
        treeland_dde_shell_surface_v1_set_role(
            m_treeland_dde_shell_surface_v1,
            role);
    }

    void treeland_dde_shell_surface_v1::set_accept_keyboard_focus(uint32_t accept)
    {
        treeland_dde_shell_surface_v1_set_accept_keyboard_focus(
            m_treeland_dde_shell_surface_v1,
            accept);
    }
}

QT_WARNING_POP
QT_END_NAMESPACE
