// This file was generated by qtwaylandscanner
// source file is treeland-dde-shell-v1.xml

#ifndef QT_WAYLAND_TREELAND_DDE_SHELL_V1
#define QT_WAYLAND_TREELAND_DDE_SHELL_V1

#include "wayland-treeland-dde-shell-v1-client-protocol.h"
#include <QByteArray>
#include <QString>

struct wl_registry;

QT_BEGIN_NAMESPACE
QT_WARNING_PUSH
QT_WARNING_DISABLE_GCC("-Wmissing-field-initializers")

namespace QtWayland {
    class  treeland_dde_shell_manager_v1
    {
    public:
        treeland_dde_shell_manager_v1(struct ::wl_registry *registry, int id, int version);
        treeland_dde_shell_manager_v1(struct ::treeland_dde_shell_manager_v1 *object);
        treeland_dde_shell_manager_v1();

        virtual ~treeland_dde_shell_manager_v1();

        void init(struct ::wl_registry *registry, int id, int version);
        void init(struct ::treeland_dde_shell_manager_v1 *object);

        struct ::treeland_dde_shell_manager_v1 *object() { return m_treeland_dde_shell_manager_v1; }
        const struct ::treeland_dde_shell_manager_v1 *object() const { return m_treeland_dde_shell_manager_v1; }
        static treeland_dde_shell_manager_v1 *fromObject(struct ::treeland_dde_shell_manager_v1 *object);

        bool isInitialized() const;

        static const struct ::wl_interface *interface();

        struct ::treeland_dde_shell_surface_v1 *get_shell_surface(struct ::wl_surface *surface);
        void destroy();

    private:
        struct ::treeland_dde_shell_manager_v1 *m_treeland_dde_shell_manager_v1;
    };

    class  treeland_dde_shell_surface_v1
    {
    public:
        treeland_dde_shell_surface_v1(struct ::wl_registry *registry, int id, int version);
        treeland_dde_shell_surface_v1(struct ::treeland_dde_shell_surface_v1 *object);
        treeland_dde_shell_surface_v1();

        virtual ~treeland_dde_shell_surface_v1();

        void init(struct ::wl_registry *registry, int id, int version);
        void init(struct ::treeland_dde_shell_surface_v1 *object);

        struct ::treeland_dde_shell_surface_v1 *object() { return m_treeland_dde_shell_surface_v1; }
        const struct ::treeland_dde_shell_surface_v1 *object() const { return m_treeland_dde_shell_surface_v1; }
        static treeland_dde_shell_surface_v1 *fromObject(struct ::treeland_dde_shell_surface_v1 *object);

        bool isInitialized() const;

        static const struct ::wl_interface *interface();

        enum role {
            role_overlay = 1,
        };

        void destroy();
        void set_surface_position(int32_t x, int32_t y);
        void set_role(uint32_t role);
        void set_accept_keyboard_focus(uint32_t accept);

    private:
        struct ::treeland_dde_shell_surface_v1 *m_treeland_dde_shell_surface_v1;
    };
}

QT_WARNING_POP
QT_END_NAMESPACE

#endif
