/* Generated by wayland-scanner 1.23.1 */

#ifndef TREELAND_DDE_SHELL_V1_CLIENT_PROTOCOL_H
#define TREELAND_DDE_SHELL_V1_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-client-core.h"

#ifdef  __cplusplus
extern "C" {
#endif

/**
 * @page page_treeland_dde_shell_v1 The treeland_dde_shell_v1 protocol
 * @section page_ifaces_treeland_dde_shell_v1 Interfaces
 * - @subpage page_iface_treeland_dde_shell_manager_v1 - dde shell manager
 * - @subpage page_iface_treeland_dde_shell_surface_v1 - metadata interface
 * @section page_copyright_treeland_dde_shell_v1 Copyright
 * <pre>
 *
 * SPDX-FileCopyrightText: 2024 UnionTech Software Technology Co., Ltd.
 * SPDX-License-Identifier: MIT
 * </pre>
 */
struct treeland_dde_shell_manager_v1;
struct treeland_dde_shell_surface_v1;
struct wl_surface;

#ifndef TREELAND_DDE_SHELL_MANAGER_V1_INTERFACE
#define TREELAND_DDE_SHELL_MANAGER_V1_INTERFACE
/**
 * @page page_iface_treeland_dde_shell_manager_v1 treeland_dde_shell_manager_v1
 * @section page_iface_treeland_dde_shell_manager_v1_desc Description
 * @section page_iface_treeland_dde_shell_manager_v1_api API
 * See @ref iface_treeland_dde_shell_manager_v1.
 */
/**
 * @defgroup iface_treeland_dde_shell_manager_v1 The treeland_dde_shell_manager_v1 interface
 */
extern const struct wl_interface treeland_dde_shell_manager_v1_interface;
#endif
#ifndef TREELAND_DDE_SHELL_SURFACE_V1_INTERFACE
#define TREELAND_DDE_SHELL_SURFACE_V1_INTERFACE
/**
 * @page page_iface_treeland_dde_shell_surface_v1 treeland_dde_shell_surface_v1
 * @section page_iface_treeland_dde_shell_surface_v1_desc Description
 * @section page_iface_treeland_dde_shell_surface_v1_api API
 * See @ref iface_treeland_dde_shell_surface_v1.
 */
/**
 * @defgroup iface_treeland_dde_shell_surface_v1 The treeland_dde_shell_surface_v1 interface
 */
extern const struct wl_interface treeland_dde_shell_surface_v1_interface;
#endif

#define TREELAND_DDE_SHELL_MANAGER_V1_GET_SHELL_SURFACE 0
#define TREELAND_DDE_SHELL_MANAGER_V1_DESTROY 1


/**
 * @ingroup iface_treeland_dde_shell_manager_v1
 */
#define TREELAND_DDE_SHELL_MANAGER_V1_GET_SHELL_SURFACE_SINCE_VERSION 1
/**
 * @ingroup iface_treeland_dde_shell_manager_v1
 */
#define TREELAND_DDE_SHELL_MANAGER_V1_DESTROY_SINCE_VERSION 2

/** @ingroup iface_treeland_dde_shell_manager_v1 */
static inline void
treeland_dde_shell_manager_v1_set_user_data(struct treeland_dde_shell_manager_v1 *treeland_dde_shell_manager_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) treeland_dde_shell_manager_v1, user_data);
}

/** @ingroup iface_treeland_dde_shell_manager_v1 */
static inline void *
treeland_dde_shell_manager_v1_get_user_data(struct treeland_dde_shell_manager_v1 *treeland_dde_shell_manager_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) treeland_dde_shell_manager_v1);
}

static inline uint32_t
treeland_dde_shell_manager_v1_get_version(struct treeland_dde_shell_manager_v1 *treeland_dde_shell_manager_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) treeland_dde_shell_manager_v1);
}

/**
 * @ingroup iface_treeland_dde_shell_manager_v1
 *
 * Create a shell surface for an existing wl_surface.
 */
static inline struct treeland_dde_shell_surface_v1 *
treeland_dde_shell_manager_v1_get_shell_surface(struct treeland_dde_shell_manager_v1 *treeland_dde_shell_manager_v1, struct wl_surface *surface)
{
	struct wl_proxy *id;

	id = wl_proxy_marshal_flags((struct wl_proxy *) treeland_dde_shell_manager_v1,
			 TREELAND_DDE_SHELL_MANAGER_V1_GET_SHELL_SURFACE, &treeland_dde_shell_surface_v1_interface, wl_proxy_get_version((struct wl_proxy *) treeland_dde_shell_manager_v1), 0, NULL, surface);

	return (struct treeland_dde_shell_surface_v1 *) id;
}

/**
 * @ingroup iface_treeland_dde_shell_manager_v1
 */
static inline void
treeland_dde_shell_manager_v1_destroy(struct treeland_dde_shell_manager_v1 *treeland_dde_shell_manager_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) treeland_dde_shell_manager_v1,
			 TREELAND_DDE_SHELL_MANAGER_V1_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) treeland_dde_shell_manager_v1), WL_MARSHAL_FLAG_DESTROY);
}

#ifndef TREELAND_DDE_SHELL_SURFACE_V1_ROLE_ENUM
#define TREELAND_DDE_SHELL_SURFACE_V1_ROLE_ENUM
/**
 * @ingroup iface_treeland_dde_shell_surface_v1
 * available roles for surfaces
 */
enum treeland_dde_shell_surface_v1_role {
	TREELAND_DDE_SHELL_SURFACE_V1_ROLE_OVERLAY = 1,
};
#endif /* TREELAND_DDE_SHELL_SURFACE_V1_ROLE_ENUM */

#define TREELAND_DDE_SHELL_SURFACE_V1_DESTROY 0
#define TREELAND_DDE_SHELL_SURFACE_V1_SET_SURFACE_POSITION 1
#define TREELAND_DDE_SHELL_SURFACE_V1_SET_ROLE 2
#define TREELAND_DDE_SHELL_SURFACE_V1_SET_ACCEPT_KEYBOARD_FOCUS 3


/**
 * @ingroup iface_treeland_dde_shell_surface_v1
 */
#define TREELAND_DDE_SHELL_SURFACE_V1_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_treeland_dde_shell_surface_v1
 */
#define TREELAND_DDE_SHELL_SURFACE_V1_SET_SURFACE_POSITION_SINCE_VERSION 1
/**
 * @ingroup iface_treeland_dde_shell_surface_v1
 */
#define TREELAND_DDE_SHELL_SURFACE_V1_SET_ROLE_SINCE_VERSION 1
/**
 * @ingroup iface_treeland_dde_shell_surface_v1
 */
#define TREELAND_DDE_SHELL_SURFACE_V1_SET_ACCEPT_KEYBOARD_FOCUS_SINCE_VERSION 1

/** @ingroup iface_treeland_dde_shell_surface_v1 */
static inline void
treeland_dde_shell_surface_v1_set_user_data(struct treeland_dde_shell_surface_v1 *treeland_dde_shell_surface_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) treeland_dde_shell_surface_v1, user_data);
}

/** @ingroup iface_treeland_dde_shell_surface_v1 */
static inline void *
treeland_dde_shell_surface_v1_get_user_data(struct treeland_dde_shell_surface_v1 *treeland_dde_shell_surface_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) treeland_dde_shell_surface_v1);
}

static inline uint32_t
treeland_dde_shell_surface_v1_get_version(struct treeland_dde_shell_surface_v1 *treeland_dde_shell_surface_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) treeland_dde_shell_surface_v1);
}

/**
 * @ingroup iface_treeland_dde_shell_surface_v1
 */
static inline void
treeland_dde_shell_surface_v1_destroy(struct treeland_dde_shell_surface_v1 *treeland_dde_shell_surface_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) treeland_dde_shell_surface_v1,
			 TREELAND_DDE_SHELL_SURFACE_V1_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) treeland_dde_shell_surface_v1), WL_MARSHAL_FLAG_DESTROY);
}

/**
 * @ingroup iface_treeland_dde_shell_surface_v1
 *
 * Move the surface to new coordinates. Coordinates are global.
 */
static inline void
treeland_dde_shell_surface_v1_set_surface_position(struct treeland_dde_shell_surface_v1 *treeland_dde_shell_surface_v1, int32_t x, int32_t y)
{
	wl_proxy_marshal_flags((struct wl_proxy *) treeland_dde_shell_surface_v1,
			 TREELAND_DDE_SHELL_SURFACE_V1_SET_SURFACE_POSITION, NULL, wl_proxy_get_version((struct wl_proxy *) treeland_dde_shell_surface_v1), 0, x, y);
}

/**
 * @ingroup iface_treeland_dde_shell_surface_v1
 *
 * Assign a role to a shell surface.
 */
static inline void
treeland_dde_shell_surface_v1_set_role(struct treeland_dde_shell_surface_v1 *treeland_dde_shell_surface_v1, uint32_t role)
{
	wl_proxy_marshal_flags((struct wl_proxy *) treeland_dde_shell_surface_v1,
			 TREELAND_DDE_SHELL_SURFACE_V1_SET_ROLE, NULL, wl_proxy_get_version((struct wl_proxy *) treeland_dde_shell_surface_v1), 0, role);
}

/**
 * @ingroup iface_treeland_dde_shell_surface_v1
 */
static inline void
treeland_dde_shell_surface_v1_set_accept_keyboard_focus(struct treeland_dde_shell_surface_v1 *treeland_dde_shell_surface_v1, uint32_t accept)
{
	wl_proxy_marshal_flags((struct wl_proxy *) treeland_dde_shell_surface_v1,
			 TREELAND_DDE_SHELL_SURFACE_V1_SET_ACCEPT_KEYBOARD_FOCUS, NULL, wl_proxy_get_version((struct wl_proxy *) treeland_dde_shell_surface_v1), 0, accept);
}

#ifdef  __cplusplus
}
#endif

#endif
