/* Generated by wayland-scanner 1.23.1 */

/*
 * SPDX-FileCopyrightText: 2024 UnionTech Software Technology Co., Ltd.
 * SPDX-License-Identifier: MIT
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

extern const struct wl_interface treeland_dde_shell_surface_v1_interface;
extern const struct wl_interface wl_surface_interface;

static const struct wl_interface *treeland_dde_shell_v1_types[] = {
	NULL,
	NULL,
	&treeland_dde_shell_surface_v1_interface,
	&wl_surface_interface,
};

static const struct wl_message treeland_dde_shell_manager_v1_requests[] = {
	{ "get_shell_surface", "no", treeland_dde_shell_v1_types + 2 },
	{ "destroy", "2", treeland_dde_shell_v1_types + 0 },
};

WL_EXPORT const struct wl_interface treeland_dde_shell_manager_v1_interface = {
	"treeland_dde_shell_manager_v1", 2,
	2, treeland_dde_shell_manager_v1_requests,
	0, NULL,
};

static const struct wl_message treeland_dde_shell_surface_v1_requests[] = {
	{ "destroy", "", treeland_dde_shell_v1_types + 0 },
	{ "set_surface_position", "ii", treeland_dde_shell_v1_types + 0 },
	{ "set_role", "u", treeland_dde_shell_v1_types + 0 },
	{ "set_accept_keyboard_focus", "u", treeland_dde_shell_v1_types + 0 },
};

WL_EXPORT const struct wl_interface treeland_dde_shell_surface_v1_interface = {
	"treeland_dde_shell_surface_v1", 1,
	4, treeland_dde_shell_surface_v1_requests,
	0, NULL,
};

